### ISSUE TITLE
Open job links in new window

### ISSUE THREAD

**Issue by TiSiE** [cross-solution/yawik-vue-joblist-widget#10]
Job ads should be opened in a new window.
At least it should be configurable how it should be done.

**Comment by cbleek** [comment]
@kilip do you have time to look at this issue?

Your widget is used now in a real website. And they you like to open jobs within a new window.

**Comment by TiSiE** [comment]
Open in a new window should be the default behaviour, with an opt-out via parameter imho.

**Comment by kilip** [comment]
@cbleek @TiSiE 

I will take a look at it tomorrow

**Comment by cbleek** [comment]
great

The customer had also noted that it would be good if the logo could be hidden.

Maybe we can also use this opportunity to make the columns configurable.

E.g. through a csv of the columns name

**Comment by kilip** [comment]
@TiSiE @cbleek 

Open job links in new window behavior can be defined using ```job-on-click```:
```html
    <yawik-job-list
            remote="https://yawik.org/demo/de/jobboard"
            org=""
            job-on-click="_blank"
    >
    </yawik-job-list>
```
Valid value for this property is: _blank, _self, _parent, _top, or a frameName as described in this [link](https://www.w3schools.com/tags/att_a_target.asp)


To hide job logo, we need to define hide-logo props to be true:
```html
    <yawik-job-list
            remote="https://yawik.org/demo/de/jobboard"
            org=""
            job-on-click="_blank"
            hide-logo
    >
    </yawik-job-list>
```

Please let me know if we need to add another custom features into this widget.
